config/routes.rb
Rails.application.routes.draw do
  resources :balances
  devise_for :accounts
  resources :extracts
  resources :accounts
  root to: "extracts#index"
  patch '/sake/balance', to: "balances#update", as: "sake_balance"
  post '/balances', to: "balances#create", as: "balances_create"
  post '/transfer/create', to: "balances#create_transfer"
  get 'transfer', to: "balances#new_beneficiary"
  patch "/accounts/:id/edit", to: "accounts#update_password", as: "edit_update_pass"
  get '/reset_password', to: "accounts#edit_password"
  post 'enable_acount', to: "accounts#enabled_account", as: "enabled_account"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.erb
<div class="form-group row">
  <div class="container-fluid">
    <div class="col-md-12 col-sm-12 col-xs-12 mx-auto">
      <br>
    </div>
  </div>
</div>

<div class="row">
  <div class="container-fluid">
    <div class="col-md-6 col-sm-1 col-xs-10 mx-auto">
      <div class="row">
        <div class="form-group col-md-12 ">
          <div class="position-absolute">
            <a class="btn btn-warning " href="/accounts/<%= current_account.id %>"><i class="fas fa-info"></i> INFORMAÇÕES DA CONTA</a>
            <a class="btn btn-warning" href="/extracts"><i class="fas fa-file-invoice-dollar"></i> EXTRATO</a>
            <a class="btn btn-warning" href="/balances/new"><i class="fas fa-hand-holding-usd"></i> DEPÓSITO</a>
            <% if @account_id_balance.present? %>
              <a class="btn btn-warning" href=/balances/<%= @account_id_balance.id %>/edit><i class="fas fa-money-bill-alt"></i> SAQUE</a>
              <a class="btn btn-warning " href="/transfer"> <i class="fas fa-exchange-alt"></i> TRANSFERÊNCIA</a>
              <a class="btn btn-warning " href="/balances/<%= @account_id_balance.id %>"><i class="fas fa-dollar-sign"></i>  SALDO</a>
            <% else %>
            <% end %>
            <a class="btn btn-danger "  rel="nofollow" data-method="DELETE" href="/accounts/sign_out">
              <i class="fa-1x fas fa-power-off"></i>
            </a>
            <a class="btn btn-light "   href="/reset_password">
              <i class="fas fa-key"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>