config/routes.rb
Rails.application.routes.draw do
  resources :balances
  devise_for :accounts
  resources :extracts
  resources :accounts
  root to: "extracts#index"
  patch '/sake/balance', to: "balances#update", as: "sake_balance"
  post '/balances', to: "balances#create", as: "balances_create"
  post '/transfer/create', to: "balances#create_transfer"
  get 'transfer', to: "balances#new_beneficiary"
  patch "/accounts/:id/edit", to: "accounts#update_password", as: "edit_update_pass"
  get '/reset_password', to: "accounts#edit_password"
  post 'enable_acount', to: "accounts#enabled_account", as: "enabled_account"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/balance.rb
class Balance < ApplicationRecord
  belongs_to :account
  validates :value,  presence: true

  def value=(value)
    if value.is_a?(String)
      value.gsub!(/[^0-9]/, "").insert(-3, '.').to_f
    end
    self[:value] = value
  end

end

app/controllers/balances_controller.rb
class BalancesController < ApplicationController
  before_action :set_balance, only: [:show]
  require 'bcrypt'

  # GET /balances/1
  # GET /balances/1.json
  def show;end

  # view for put transfer
  def new_beneficiary;end

  # GET /balances/new
  def new
    @balance = Balance.new
  end

  # GET /balances/1/edit
  def edit
    @balance = Balance.where(id: params[:id]).take
  end

  def create
    @balance = Balance.where(account_id: current_account.id).take
    if params[:balance][:value].to_s.gsub!(/[^0-9]/, '').insert(-3, '.').to_f == 0.0
      flash[:error] = 'Insira um valor maior que 0'
      redirect_to new_balance_path
    else
      if @balance.present?
        new_value = params[:balance][:value].to_s.gsub!(/[^0-9]/, '').insert(-3, '.').to_f
        new_value = @balance.value + new_value
        Balance.where(id: @balance.id).update(value: new_value)
        Extract.create(account_id: current_account.id, description: 'Depósito', donate: current_account.agency, beneficiary: nil, amount: params[:balance][:value], rate: 0)
        flash[:success] = 'Depósito realizado!'
        redirect_to extracts_path
      else
        @balance = Balance.new(balance_params.merge(account_id: current_account.id))
        if @balance.save
          Extract.create(account_id: current_account.id, description: 'Depósito', donate: current_account.agency, beneficiary: nil, amount: params[:balance][:value], rate: 0)
          flash[:success] = 'Depósito realizado!'
          redirect_to extracts_path
        else
          flash[:error] = 'Erro ao ralizar Depósito!'
          redirect_to new_balance_path
        end
      end
    end
  end

  def create_transfer
    beneficiary = Account.where(agency: params[:beneficiary]).take
    account_setings = Account.find(current_account.id)
    value = params[:value].to_s.gsub!(/[^0-9]/, '').insert(-3, '.').to_f
    #validando senha
    if account_setings.valid_password?(params[:password].to_s)
      account_balance = Balance.where(account_id: account_setings.id).take
      # beneficiary exist ?
      if beneficiary.present?
        #account same beneficiary
        if account_setings.agency == params[:beneficiary].to_i
          flash[:error] = 'Favorecido não pode ser depositante!'
          render json: false
        else
          rate = ToolsServices.new.set_rate(value)
          value_and_rate_by_rage = ToolsServices.new.set_rate_by_value(value, rate)
          #afte rate get account balance and verify if exist balance
          if account_balance.value > value_and_rate_by_rage
              ToolsServices.new.set_extract_donate(current_account.id, "Transferência", current_account.agency, params[:beneficiary], value_and_rate_by_rage, rate)
              ToolsServices.new.discout_balance_donate(value_and_rate_by_rage, current_account.id)
              ToolsServices.new.set_extract_donate(beneficiary.id, "Depósito", current_account.agency, params[:beneficiary], value_and_rate_by_rage, rate)
              ToolsServices.new.add_balance_beneficiary(value_and_rate_by_rage, beneficiary.id)
              flash[:success] = 'Transferência realizada!'
              render json: true
          else
            flash[:error] = 'Sem saldo na conta!'
            render json: false

          end
        end
      else
        flash[:error] = 'Conta inválida!'
        render json: false

      end
    else
      flash[:error] = 'Senha inválida!'
      render json: false
    end
  end

  def update
    @balance = Balance.where(account_id: current_account.id).take
    new_value_sake = @balance.value - params[:balance][:value].to_s.gsub!(/[^0-9]/, "").insert(-3, '.').to_f
    if params[:balance][:value].to_s.gsub!(/[^0-9]/, "").insert(-3, '.').to_f == 0.0
      flash[:error] = 'Insira um valor maior que 0'
      redirect_to edit_balance_path(@balance.id)
    else
      if new_value_sake < 0
        flash[:error] = 'Sem saldo na conta!'
        redirect_to edit_balance_path(@balance.id)
      else
        if @balance.update(balance_params.merge(value: new_value_sake))
          Extract.create(account_id: current_account.id, description: "Saque", donate: current_account.agency, beneficiary: nil, amount: params[:balance][:value], rate: 0)
          flash[:success] = 'Saque realizado!'
          redirect_to extracts_path
        else
          flash[:error] = 'Erro ao realizar saque!'
          redirect_to edit_balance_path(@balance.id)
        end
      end
    end

  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_balance
    @balance = Balance.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def balance_params
    params.except(:password)
    params.require(:balance).permit(:value, :account_id, :password)
  end
end

app/helpers/balances_helper.rb
module BalancesHelper
end

app/views/balances/_form.html.erb
<%= form_for(@balance, url: balances_create_path, method: "post", class: "form-inline") do |form| %>
  <div class="form-inline  mb-2">
    <%= form.text_field :value, class: "form-control money" %>
    <%= form.button class: "btn btn-success" do %>
      <i class="fas fa-check"></i>
    <% end %>
  </div>
<% end %>

app/views/balances/edit.html.erb
<div class="form-group row">
  <div class="container-fluid">
    <div class="col-md-5  mx-auto">
      <h2>Saque em conta</h2>
      <div class="text-center">
        <%= form_for @balance, url: sake_balance_path, method: "patch" do |form| %>
          <div class="form-inline  mb-2">
            <%= form.text_field :value, class: "form-control money", value: "0,0" %>
            <%= form.button class: "btn btn-success" do %>
              <i class="fas fa-check"></i>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/balances/new.html.erb
<div class="form-group row">
  <div class="container-fluid">
    <div class="col-md-5  mx-auto">
      <h2 >Novo depósito</h2>
      <div class="text-center">
        <%= render 'form', balance: @balance.value %>
      </div>
    </div>
  </div>
</div>

app/views/balances/new_beneficiary.html.erb
<%= javascript_include_tag 'balances', 'data-turbolinks-track': 'reload' %>
<div class="form-group row">

  <div class="container-fluid">
    <div class="col-md-5  mx-auto">
      <h2>Transferencia entre contas</h2>
      <form >
        <div class="text-center">
          <div class="form-group  mb-2">
            <label for="">Beneficiado</label>
            <input type="text" value="" id="beneficiary" name="beneficiary" class="form-control" maxlength="7">
            <label for="">Valor:</label>
            <input type="text" value="" id="value" name="value" class="form-control money">
            <label for="">Senha:</label>
            <input type="password" value="" id="password" name="password" class="form-control">
            <br>
            <button type="submit" class="btn btn-success" id="save"><i class="fas fa-check"> Transferir</i>
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/balances/show.html.erb
<div class="form-group">
  <div class="text-center">
  <p>
    <strong>SALDO</strong>
  </p>
  </div>
  <div class="text-center text-success">
    <%= number_to_currency_br(@balance.value.to_s) %>
  </div>
</div>