config/routes.rb
Rails.application.routes.draw do
  resources :balances
  devise_for :accounts
  resources :extracts
  resources :accounts
  root to: "extracts#index"
  patch '/sake/balance', to: "balances#update", as: "sake_balance"
  post '/balances', to: "balances#create", as: "balances_create"
  post '/transfer/create', to: "balances#create_transfer"
  get 'transfer', to: "balances#new_beneficiary"
  patch "/accounts/:id/edit", to: "accounts#update_password", as: "edit_update_pass"
  get '/reset_password', to: "accounts#edit_password"
  post 'enable_acount', to: "accounts#enabled_account", as: "enabled_account"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stark Bank</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag "//stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css", media: "all", "data-turbolinks-track": "reload" %>
  <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.2.1/css/bootstrap-grid.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag "//use.fontawesome.com/releases/v5.6.3/css/all.css", media: "all", "data-turbolinks-track": "reload" %>
  <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css", media: "all", "data-turbolinks-track": "reload" %>
  <%= stylesheet_link_tag "vali-admin", "data-turbolinks-track": "reload" %>
  <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>

  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/jquery-maskmoney/3.0.2/jquery.maskMoney.min.js", "data-turbolinks-track": "reload" %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.2.1/js/bootstrap.min.js', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-treeview/1.2.0/bootstrap-treeview.min.js', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/pace/1.0.2/pace.min.js', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= yield :javascript %>
</head>
<% if account_signed_in? %>
  <body style="background: #7f7f7f">
  <div class="col-md-12" style="background:  #7f7f7f;">
    <%= render 'shared/navbar' %>
    <br>
    <br>
    <div class="row">
      <div class="container-fluid">
        <div class="col-md-6 col-sm-10 col-xs-12 mx-auto">
          <div class="tile" style="font-size: x-large;">
            <%= flash_message %>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </div>
  </body>
<% else %>
  <body >

  <section class="material-half-bg">
    <div class="cover"></div>
  </section>
  <%= yield %>
  </body>
<% end %>

</html>