config/routes.rb
Rails.application.routes.draw do
  resources :balances
  devise_for :accounts
  resources :extracts
  resources :accounts
  root to: "extracts#index"
  patch '/sake/balance', to: "balances#update", as: "sake_balance"
  post '/balances', to: "balances#create", as: "balances_create"
  post '/transfer/create', to: "balances#create_transfer"
  get 'transfer', to: "balances#new_beneficiary"
  patch "/accounts/:id/edit", to: "accounts#update_password", as: "edit_update_pass"
  get '/reset_password', to: "accounts#edit_password"
  post 'enable_acount', to: "accounts#enabled_account", as: "enabled_account"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :cpf, :email, presence: true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def show
      @account = current_account
  end


  # GET /accounts/1/edit
  def edit
    @account = current_account
  end

  def edit_password
    @account = current_account
  end

  def update_password
    @account = current_account
    if @account.present?
      if @account.update(account_params)
        bypass_sign_in(@account)
        flash[:success] = 'Atualizada com sucesso!'
        redirect_to root_path
      else
        flash[:warning] = 'Erro ao atualizar senha (Mínimo 6 caracters), vefique os campos!'
        redirect_to accounts_reset_password_path
      end
    else
      flash[:warning] = 'Vefirique os campos'
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    if @account.update(account_params)
      flash[:success] = 'Atualizada com sucesso!'
      redirect_to root_path
    else
      flash[:error] = 'Conta não atualizada!'
      edit_account_path
    end
  end


  def enabled_account
    Account.where(id: current_account).update(status: false)
    flash[:success] = 'Sua conta foi cancelada com sucesso!'
    sign_out(current_account)
    redirect_to root_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_account
    @account = Account.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def account_params
    params.require(:account).permit(:phone, :agency, :cpf, :status, :balance)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>

  <div class="form-group row">
    <div class="col-md-6">
      <label for="">CPF </label>
      <%= form.text_field :cpf, class: "form-control cpf" %>
    </div>
    <div class="col-md-6">
      <label for="">Email </label>
      <%= form.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="text-center row">
    <div class="col-md-2 ">
      <%= form.button class: "btn btn-success" do %>
        <i class="fa fa-fw fa-lg fa-check-circle"></i> Atualizar conta
      <% end %>
    </div>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h3 class="tile-title text-center">Edita minha conta</h3>

<%= render 'form', account: @account %>

app/views/accounts/edit_password.html.erb
<%= form_for @account, url: edit_update_pass_path(@account), action: :update_password do |f| %>
  <div class="card">
    <div class="card-body">
      <div class="col-md-12">
        <div class="form-group row">
          <%= f.label :"Nova senha", class: "control-label col-md-4 " %>
          <div class="col-md-6">
            <%= f.text_field :password, autofocus: true, type: 'password', class: "form-control usertext" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :"Confirme sua senha", class: "control-label col-md-4" %>
          <div class="col-md-6">
            <%= f.text_field :password_confirmation, autofocus: true, type: 'password', class: "form-control " %>
          </div>
        </div>
        <div class="form-group row">
          <div class="clearfix col-md-6">
            <%= f.button class: "btn btn-success" do %>
              <i class="fa fa-fw fa-lg fa-check-circle"></i> Atualizar senha
            <% end %>
          </div>
        </div>
      </div>

    </div>
  </div>
<% end %>

app/views/accounts/show.html.erb
<h3 class="tile-title text-center">Minha conta</h3>
<div class="form-group row">
  <div class="col-md-6">
    <label for="">Agencia </label>
    <input type="text" class="form-control" value="<%= @account.agency %> " disabled>
  </div>
  <div class="col-md-6">
    <label for="">CPF</label>
    <input type="text" class="form-control " value="<%= @account.cpf %> " disabled>
  </div>
</div>

<div class="form-inline">
    <%= link_to 'Cancelar conta', enabled_account_path, class: "btn btn-danger shadow-lg ", data: {method: "post"} %>
    <%= link_to 'Edita minha conta', edit_account_path(@account), class: "btn btn-ligth shadow-lg " %>
</div>